### ISSUE TITLE
디바이스 목록 다이얼로그를 dismiss 한 이후 다시 띄우는 방법이 직관적이지 않다

### ISSUE THREAD

**Issue by jihyeon-rainbow** [kam6512/BT_Scanner#12]
네비게이션 뷰 에서 '기기'를 선택하거나 pull to refresh 해야 해당 다이얼로그를 다시 띄울 수 있다.

**Comment by jihyeon-rainbow** [comment]
네비게이션 뷰: '기기'를 선택하면 현재 연결된 기기가 아니라, 장비 목록이 표시된다

**Comment by kam6512** [comment]
- 기기 변경하기로 메뉴 수정됨
- 연결된 기기는 네비게이션 헤더에 표시됨 확인

기기 연결이 안 된 상태에서는 "기기 연결하기"로 표시하는게 맞음 일단은 그냥 가자.
