### ISSUE TITLE
최초 실행후 back 키 종료시 강제종료 발생함

### ISSUE THREAD

**Issue by jihyeon-rainbow** [kam6512/BT_Scanner#9]
장비 연결이 안 되어 있거나 앱 설치 후 최초 실행 후 바로 back 키 입력하면 강제종료된다.

**Comment by kam6512** [comment]
https://github.com/kam6512/BT_Scanner/commit/3199c78e3ce68ff68667217c04e9d8ccc944b47a 에서 수정됨
